{% set version = "12.6.3" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 12.6.77
    - cuda-nvrtc 12.6.85
    - cuda-opencl 12.6.77    # [linux64 or win]
    - libcublas 12.6.4.1
    - libcufft 11.3.0.4 
    - libcufile 1.11.1.6       # [linux]
    - libcurand 10.3.7.77
    - libcusolver 11.7.1.2
    - libcusparse 12.5.4.2
    - libnpp 12.3.1.54
    - libnvfatbin 12.6.77
    - libnvjitlink 12.6.85
    - libnvjpeg 12.3.3.54

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
