{% set version = "12.5.1" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 12.5.82
    - cuda-nvrtc 12.5.82
    - cuda-opencl 12.5.39    # [linux64 or win]
    - libcublas 12.5.3.2
    - libcufft 11.2.3.61 
    - libcufile 1.10.1.7       # [linux]
    - libcurand 10.3.6.82
    - libcusolver 11.6.3.83
    - libcusparse 12.5.1.3
    - libnpp 12.3.0.159
    - libnvfatbin 12.5.82
    - libnvjitlink 12.5.82
    - libnvjpeg 12.3.2.81

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
