{% set version = "12.5.0" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart 12.5.39
    - cuda-nvrtc 12.5.40
    - cuda-opencl 12.5.39    # [linux64 or win]
    - libcublas 12.5.2.13
    - libcufft 11.2.3.18 
    - libcufile 1.10.0.4       # [linux64 or aarch64]
    - libcurand 10.3.6.39
    - libcusolver 11.6.2.40
    - libcusparse 12.4.1.24
    - libnpp 12.3.0.116
    - libnvfatbin 12.5.39
    - libnvjitlink 12.5.40
    - libnvjpeg 12.3.2.38

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
